name = "SheetModel"
uuid = "3921df55-cb7d-45ab-ac85-2571596d0d4e"
authors = ["Annegret Pohle <apohle@ethz.ch>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
